### PR TITLE
Store abbreviated git hash as SSI Info for load modules

### PR DESCRIPTION
**Pull request by dennis-behm**
This enhancement retrieves the current abbreviated git hash for changed and impacted files for the following build types: fullBuild, impactBuild and mergeBuild.

Several areas are updated in buildUtils and impactUtils to populate a PropertyMappings  object `githashBuildableFilesMap` to store a DBB build property map with these information.

The language scripts pass the abbreviated hash to the linker.

It also supports builds across multiple repositories:

image

### CODE REVIEW

**Review by drbruce-git — COMMENTED** [review]
So it looks like this change to add Git Hash SSI to load modules is not optional.  What if the customer is using the SSI for other purposes?  Shouldn't there be an option to turn this off or default is off and option to turn it on?

**Comment by dennis-behm** [comment]
@drbruce-git I introduced a flag to turn it on and off. Can you please have another check?

**Review by drbruce-git — APPROVED** [review]

**Comment by jbyibm** [comment]
@dennis-behm We may have an interest for PLUM here. 
Quick question:
- the --short=8 option is a truncation of the real githash ? or something that we can consider as an unique identifier?

**Comment by dennis-behm** [comment]
> @dennis-behm We may have an interest for PLUM here. Quick question:
> 
> * the --short=8 option is a truncation of the real githash ? or something that we can consider as an unique identifier?

Hi @jbyibm 

This performs a `git rev-parse --short=8 HEAD` in the GitUtilities. It is a truncated part of the full git hash:

```
git rev-parse --short=8 HEAD                                   
5e3ccd2f

git rev-parse HEAD                  
5e3ccd2f43c18cd0dc3ba837121bcd0f50970275
```

**Pull request merged**
