### PR TITLE
Mkdocs material

### PR DESCRIPTION
**Pull request by ijmitch**
Goodness... I should have described the intent here!

This turns the Markdown files into a Github Pages site generated using Mkdocs so we get:
image

rather than the default rendering of the source.

### CODE REVIEW

**Comment by ijmitch** [comment]
BTW, this is pretty much the same as I did for https://ibm.github.io/tnz/

**Comment by dennis-behm** [comment]
@ijmitch I have modified the target branch of the PR to be `develop` instead of `main`, which is now leading to some merge conflicts. Can you please take care of them?

**Comment by ijmitch** [comment]
I will have a go!

**Comment by ijmitch** [comment]
Fixed the merge conflicts but also the links from doc back into other types of source files in the repo.

**Comment by ijmitch** [comment]
In Settings for the repo, you need to update the 'Pages' setting to match...
image

Which should just mean setting the source to deploy from the gh-pages branch.

**Comment by ijmitch** [comment]
hmm... the fixed links which worked in my local environment are failing on https://ijmitch.github.io/dbb-zappbuild/ - work to do.

**Comment by ijmitch** [comment]
> hmm... the fixed links which worked in my local environment are failing on https://ijmitch.github.io/dbb-zappbuild/ - work to do.

I needed to cherry-pick one more commit from the working branch into `main` in order for the links to work in the build. 

Now basically all working on https://ijmitch.github.io/dbb-zappbuild/

**Comment by ijmitch** [comment]
Closing this.

Docusaurus might be a better option.

**Pull request closed without merging**
