### PR TITLE
Simplify obtaining the playbackDependency

### PR DESCRIPTION
**Pull request by dennis-behm**
This is simplifying the ZUnitConfig.groovy and fixes #390

### CODE REVIEW

**Review by drbruce-git — CHANGES_REQUESTED** [review]
What was the result of running the automated zAppBuild tests?
Does it make sense to add new test cases for this code change?

**Comment by dennis-behm** [comment]
@drbruce-git 
I agree, that a new test case for this section of the code makes sense. However, the code change is very small. 
I think it requires to add a new test application, which includes a IDZ zunit test configuration. Let's treat this as a separate issue. Would you be okay with this approach?

**Comment by drbruce-git** [comment]
@dennis-behm OK we can table the new test case for zunit testing for later.  However can we still get the results of the existing regression tests?  Also we need to figure out how to add a successful regression test run to the PR checks.

**Comment by dennis-behm** [comment]
@drbruce-git 

Here is the test bucket, which I ran against my branch:

This is the repo:

```
Cloning the remote Git repository
Cloning repository https://github.com/dennis-behm/dbb-zappbuild.git
 > git init /var/jenkins/workspace/dbb-zappbuild-testframework-withParms # timeout=10
Fetching upstream changes from https://github.com/dennis-behm/dbb-zappbuild.git
 > git --version # timeout=10
 > git --version # 'git version 2.26.2-78'
 > git fetch --tags --force --progress -- https://github.com/dennis-behm/dbb-zappbuild.git +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
Checking out Revision 0ad49d4b93a51ee6b62ec22a985030bcf1f9d26e (origin/309_Zunit_without_playbackfile_develop)
Commit message: "Simplify obtaining the playbackDependency"
First time build. Skipping changelog.
```

My (testing) pipeline includes a full build for our internal catalog application:

```
*** Resolution rules for catalog-manager/testcfg/DFH0XVDS.bzucfg:
search:[SYSPLAY:]/var/jenkins/workspace/dbb-zappbuild-testframework-withParms/catalog-manager/?path=catalog-manager/testplayfiles/*.plbck
*** Physical dependencies for catalog-manager/testcfg/DFH0XVDS.bzucfg:
{"excluded":true,"lname":"DFH0XVDS","library":"SYSPROG","category":"ZUNITINC","resolved":false}
{"excluded":true,"lname":"TDFH0XVD","library":"SYSTEST","category":"ZUNITINC","resolved":false}
{"excluded":false,"sourceDir":"\/var\/jenkins\/workspace\/dbb-zappbuild-testframework-withParms\/catalog-manager\/","lname":"DFH0XVDS","library":"SYSPLAY","file":"catalog-manager\/testplayfiles\/DFH0XVDS.plbck","category":"ZUNITINC","resolved":true}
//RUNZUNIT JOB ,MSGCLASS=H,CLASS=A,NOTIFY=&SYSUID,REGION=0M
//*
//BADRC   EXEC PGM=IEFBR14
//DD        DD DSN=&SYSUID..BADRC,DISP=(MOD,CATLG,DELETE),
//             DCB=(RECFM=FB,LRECL=80),UNIT=SYSALLDA,
//             SPACE=(TRK,(1,1),RLSE)
//*
//* Action: Run Test Case...
//RUNNER EXEC PROC=BZUPPLAY,
// BZUCFG=JENKINS.DBB.TEST.CTLGMGR.BZU.BZUCFG(DFH0XVDS),
// BZUCBK=JENKINS.DBB.TEST.CTLGMGR.TEST.LOAD,
// BZULOD=JENKINS.DBB.TEST.CTLGMGR.LOAD,
//  PARM=('STOP=E,REPORT=XML,TIMESTAMP=C')
//REPLAY.BZUPLAY DD DISP=SHR, 
// DSN=JENKINS.DBB.TEST.CTLGMGR.BZU.BZUPLAY(DFH0XVDS)   < .....<...... JCL is correctly inserting the playback file name
//REPLAY.BZURPT DD DISP=SHR,
// DSN=JENKINS.DBB.TEST.CTLGMGR.BZU.BZURPT(DFH0XVDS)
//*
//IFGOOD IF RC<=4 THEN
//GOODRC  EXEC PGM=IEFBR14
//DD        DD DSN=&SYSUID..BADRC,DISP=(MOD,DELETE,DELETE),
//             DCB=(RECFM=FB,LRECL=80),UNIT=SYSALLDA,
//             SPACE=(TRK,(1,1),RLSE)
//       ENDIF

***  zUnit Test Job RUNZUNIT(JOB00543) completed with 0 
****************** Module [TDFH0XVD] ******************
Name:       TDFH0XVD
Status:     pass
Test cases: 1 (1 passed, 0 failed, 0 errors)
```

**Review by drbruce-git — APPROVED** [review]

**Pull request merged**
